version: '3.0'
services:
  instant-stock:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    container_name: instant-stock-backend
    depends_on:
      - "dynamodb"
    env_file:
      - local_secrets.env
  dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal
    hostname: dynamodb-local
    container_name: dynamodb-local
    volumes:
      - dynamodb:/home/dynamodblocal
    ports:
      - "8000:8000"
volumes:
  dynamodb:
